import { useState, useCallback, useRef, useEffect, useMemo } from 'react';
import { useExpenses, useCreateExpense, useUpdateExpense, useDeleteExpense } from '@/hooks/useExpenses';
import { useBookings } from '@/hooks/useBookings';
import { useTrip } from '@/hooks/useTrips';
import { useEngagements } from '@/hooks/useEngagements';
import { useUserProfile } from '@/hooks/useUserProfile';
import { Expense, ExpenseCategory, ExpenseSubCategory, ExpensePurpose } from '@/types/database';
import { BusinessOnly } from '@/components/access';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { 
  calculateCategorySummary,
  getExpenseMyShare,
  logExpenseDebug,
  calculateTripCostSummary,
  calculateExpensePurposeBreakdown,
  normalizeFlightBookingCosts,
  calculateNormalizedExpenseTotals,
  getNormalizedExpenseAmount,
  getNormalizedExpenseMyShare,
  isForeignCurrencyExpense,
  isConvertedExpense,
} from '@/lib/expenseCalculations';
import { formatCurrency, MY_SHARE_LABEL } from '@/lib/displayFormats';
import { BusinessPersonalSummary } from '@/components/trips/BusinessPersonalSummary';
import { isAutoGeneratedExpense, getCleanNotesForDisplay } from '@/lib/bookingExpenseSync';
import { hasCurrencyAssumedFlag } from '@/lib/currencyNormalization';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Plus, Trash2, Receipt, Utensils, Car, PartyPopper, ShoppingBag, 
  ParkingCircle, MoreHorizontal, Upload, Sparkles, Camera, AlertCircle,
  CheckCircle, RefreshCw, Image as ImageIcon, Fuel, Link2, Pencil,
  Briefcase, Home, MapPin
} from 'lucide-react';
import { ManualStepHint, MANUAL_STEP_HINTS } from '@/components/trips/ManualStepHint';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { GasExpenseDialog } from '@/components/trips/GasExpenseDialog';
import { format, parseISO } from 'date-fns';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useTripPermission } from '@/pages/TripDetail';
import { ParseOriginHint, inferExpenseOrigin } from '@/components/trips/ParseHint';

interface ExpensesTabProps {
  tripId: string;
  /** v2.3.5: Signal to auto-open Add Expense dialog from mobile field card */
  autoOpenAdd?: boolean;
  onAutoOpenConsumed?: () => void;
}

const SUB_CATEGORIES: Record<ExpenseCategory, { value: ExpenseSubCategory; label: string }[]> = {
  meals: [
    { value: 'breakfast', label: 'Breakfast' },
    { value: 'lunch', label: 'Lunch' },
    { value: 'dinner', label: 'Dinner' },
    { value: 'snacks', label: 'Snacks' },
    { value: 'coffee', label: 'Coffee' },
    { value: 'groceries', label: 'Groceries' },
    { value: 'alcohol', label: 'Alcohol' },
    { value: 'beverages', label: 'Beverages' },
  ],
  transport: [
    { value: 'uber', label: 'Uber/Lyft' },
    { value: 'taxi', label: 'Taxi' },
    { value: 'gas', label: 'Gas' },
    { value: 'tolls', label: 'Tolls' },
    { value: 'public_transit', label: 'Public Transit' },
    { value: 'rental_car', label: 'Rental Car' },
  ],
  activity: [
    { value: 'tours', label: 'Tours' },
    { value: 'entertainment', label: 'Entertainment' },
    { value: 'tickets', label: 'Tickets' },
    { value: 'sports', label: 'Sports' },
  ],
  shopping: [
    { value: 'souvenirs', label: 'Souvenirs' },
    { value: 'clothing', label: 'Clothing' },
    { value: 'gifts', label: 'Gifts' },
  ],
  parking: [
    { value: 'parking_expense', label: 'Parking Fee' },
  ],
  other: [
    { value: 'tips', label: 'Tips' },
    { value: 'fees', label: 'Fees' },
    { value: 'insurance', label: 'Insurance' },
    { value: 'miscellaneous', label: 'Miscellaneous' },
  ],
};

export function ExpensesTab({ tripId, autoOpenAdd, onAutoOpenConsumed }: ExpensesTabProps) {
  const { canEdit, canAddExpenses } = useTripPermission();
  // v3.9.5: Use canAddExpenses for expense write gate (capability-scoped)
  const canWriteExpenses = canAddExpenses || canEdit;
  const { data: expenses = [], isLoading } = useExpenses(tripId);
  const { data: bookings = [], isLoading: bookingsLoading } = useBookings(tripId);
  const { data: trip } = useTrip(tripId);
  const { data: engagements = [] } = useEngagements(tripId); // Patch 2.3.8: Fetch Stops for selector
  const { data: userProfile } = useUserProfile();
  const homeCurrency = userProfile?.preferred_currency || 'USD';
  const createExpense = useCreateExpense();
  const updateExpense = useUpdateExpense();
  const deleteExpense = useDeleteExpense();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingExpense, setEditingExpense] = useState<Expense | null>(null); // v1.3.1: Track editing state
  const [expenseToDelete, setExpenseToDelete] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<string>('all');
  const [activePurposeFilter, setActivePurposeFilter] = useState<'all' | 'business' | 'personal'>('all');
  const [parsing, setParsing] = useState(false);
  const [parseError, setParseError] = useState<string | null>(null);
  const [parseSuccess, setParseSuccess] = useState(false);
  const [previewImage, setPreviewImage] = useState<string | null>(null);
  const [uploadingImage, setUploadingImage] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const cameraInputRef = useRef<HTMLInputElement>(null);

const [gasDialogOpen, setGasDialogOpen] = useState(false);


  const [formData, setFormData] = useState({
    date: format(new Date(), 'yyyy-MM-dd'),
    category: 'meals' as ExpenseCategory,
    sub_category: '' as ExpenseSubCategory | '',
    description: '',
    amount: '',
    my_share: '',
    notes: '',
    receipt_url: '',
    expense_purpose: '' as ExpensePurpose | '',
    engagement_id: '' as string,
    currency: homeCurrency, // v4.4.2: Currency for the expense
    converted_amount: '', // v4.4.2: Manual conversion amount in home currency
  });

  const resetForm = () => {
    setFormData({
      date: format(new Date(), 'yyyy-MM-dd'),
      category: 'meals' as ExpenseCategory,
      sub_category: '',
      description: '',
      amount: '',
      my_share: '',
      notes: '',
      receipt_url: '',
      expense_purpose: '',
      engagement_id: '',
      currency: homeCurrency,
      converted_amount: '',
    });
    setPreviewImage(null);
    setParseError(null);
    setParseSuccess(false);
  };

  // v2.3.5: Auto-open Add Expense dialog when signaled from mobile field card
  useEffect(() => {
    if (autoOpenAdd) {
      resetForm();
      setEditingExpense(null);
      setDialogOpen(true);
      onAutoOpenConsumed?.();
    }
  }, [autoOpenAdd]);

  // Quick-add opens dialog with pre-selected category/subcategory
  const openQuickAdd = (category: ExpenseCategory, subCategory: ExpenseSubCategory) => {
    setFormData({
      date: format(new Date(), 'yyyy-MM-dd'),
      category,
      sub_category: subCategory,
      description: '',
      amount: '',
      my_share: '',
      notes: '',
      receipt_url: '',
      expense_purpose: '',
      engagement_id: '',
      currency: homeCurrency,
      converted_amount: '',
    });
    setPreviewImage(null);
    setParseError(null);
    setParseSuccess(false);
    setDialogOpen(true);
  };

  // v1.3.1: Open edit dialog with expense data pre-populated
  const openEdit = (expense: Expense) => {
    setEditingExpense(expense);
    setFormData({
      date: expense.date,
      category: expense.category as ExpenseCategory,
      sub_category: (expense.sub_category || '') as ExpenseSubCategory | '',
      description: expense.description || '',
      amount: expense.amount.toString(),
      my_share: expense.my_share?.toString() || '',
      notes: getCleanNotesForDisplay(expense.notes) || '',
      receipt_url: expense.receipt_url || '',
      expense_purpose: (expense.expense_purpose || '') as ExpensePurpose | '',
      engagement_id: expense.engagement_id || '',
      currency: (expense as any).currency || homeCurrency,
      converted_amount: expense.converted_amount?.toString() || '',
    });
    setPreviewImage(expense.receipt_url || null);
    setParseError(null);
    setParseSuccess(false);
    setDialogOpen(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // v1.3.0: Validate expense_purpose is set for mixed trips
    const isMixedTrip = trip?.trip_type === 'mixed';
    if (isMixedTrip && !formData.expense_purpose) {
      toast.error('Please select Business or Personal for this expense');
      return;
    }
    
    const amount = parseFloat(formData.amount) || 0;
    // Default my_share to total amount if not specified or empty
    const myShare = formData.my_share && formData.my_share.trim() !== '' 
      ? parseFloat(formData.my_share) 
      : amount;

    // v4.4.2: Determine converted amount for foreign currency expenses
    const isForeign = formData.currency.toUpperCase() !== homeCurrency.toUpperCase();
    const parsedConverted = formData.converted_amount ? parseFloat(formData.converted_amount) : null;
    const convertedAmount = isForeign && parsedConverted && parsedConverted > 0 ? parsedConverted : null;
    const convertedCurrency = convertedAmount ? homeCurrency : null;
    
    // v1.3.1: Handle edit vs create
    if (editingExpense) {
      await updateExpense.mutateAsync({
        id: editingExpense.id,
        trip_id: tripId,
        date: formData.date,
        category: formData.category,
        sub_category: formData.sub_category || 'miscellaneous',
        description: formData.description || undefined,
        amount: amount,
        my_share: myShare,
        notes: formData.notes || undefined,
        receipt_url: formData.receipt_url || undefined,
        expense_purpose: isMixedTrip && formData.expense_purpose ? formData.expense_purpose : undefined,
        engagement_id: formData.engagement_id || null,
        currency: formData.currency || homeCurrency,
        converted_amount: convertedAmount,
        converted_currency: convertedCurrency,
      } as any);
    } else {
      await createExpense.mutateAsync({
        trip_id: tripId,
        date: formData.date,
        category: formData.category,
        sub_category: formData.sub_category || 'miscellaneous',
        description: formData.description || undefined,
        amount: amount,
        my_share: myShare,
        notes: formData.notes || undefined,
        receipt_url: formData.receipt_url || undefined,
        expense_purpose: isMixedTrip && formData.expense_purpose ? formData.expense_purpose : undefined,
        engagement_id: formData.engagement_id || undefined,
        currency: formData.currency || homeCurrency,
        converted_amount: convertedAmount,
        converted_currency: convertedCurrency,
      } as any);
    }
    
    resetForm();
    setEditingExpense(null);
    setDialogOpen(false);
  };

  const handleDelete = () => {
    if (expenseToDelete) {
      deleteExpense.mutate({ id: expenseToDelete, trip_id: tripId });
      setExpenseToDelete(null);
    }
  };

  // Handle image file selection (from camera or file picker)
  const handleImageSelect = useCallback(async (file: File) => {
    setParseError(null);
    setParseSuccess(false);
    setUploadingImage(true);
    
    try {
      // Validate file type
      if (!file.type.startsWith('image/')) {
        setParseError('Please select an image file');
        return;
      }

      // Validate file size (max 10MB)
      if (file.size > 10 * 1024 * 1024) {
        setParseError('Image must be less than 10MB');
        return;
      }

      // Create preview
      const reader = new FileReader();
      reader.onload = (e) => {
        setPreviewImage(e.target?.result as string);
      };
      reader.readAsDataURL(file);

      // Upload to storage
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const fileName = `${user.id}/${Date.now()}_${file.name}`;
      const { error: uploadError, data: uploadData } = await supabase.storage
        .from('receipts')
        .upload(fileName, file);

      if (uploadError) throw uploadError;

      // Get a signed URL for the uploaded image (1 hour expiry for defense-in-depth)
      const { data: signedUrlData, error: signedUrlError } = await supabase.storage
        .from('receipts')
        .createSignedUrl(fileName, 3600);

      if (signedUrlError) throw signedUrlError;
      
      setFormData(prev => ({ ...prev, receipt_url: signedUrlData.signedUrl }));

      // Convert to base64 for AI parsing
      const base64Reader = new FileReader();
      base64Reader.onload = async (e) => {
        const base64Data = (e.target?.result as string).split(',')[1];
        await parseReceiptImage(base64Data);
      };
      base64Reader.readAsDataURL(file);

    } catch (error) {
      console.error('Image upload error:', error);
      setParseError('Failed to upload image. Please try again.');
    } finally {
      setUploadingImage(false);
    }
  }, []);

  // Parse receipt image with AI
  const parseReceiptImage = async (base64Data: string) => {
    setParsing(true);
    setParseError(null);
    
    try {
      const { data, error } = await supabase.functions.invoke('parse-receipt-image', {
        body: { imageBase64: base64Data },
      });

      // Handle network-level errors
      if (error) {
        console.error('Network error:', error);
        setParseError('Unable to connect. Please check your connection and try again.');
        toast.error('Connection error');
        return;
      }

      // Handle unreadable receipts
      if (data?.readable === false) {
        const message = data.retryMessage || data.message || 'Unable to read receipt';
        setParseError(message);
        toast.error(data.message || 'Unable to read receipt');
        return;
      }
      
      // Handle low confidence - still populate but warn user
      if (data?.lowConfidence && data?.data) {
        const parsed = data.data;
        
        // Build notes from breakdown even for low confidence
        const noteParts: string[] = [];
        if (parsed.location) noteParts.push(`📍 ${parsed.location}`);
        if (parsed.subtotal) noteParts.push(`Subtotal: $${parsed.subtotal.toFixed(2)}`);
        if (parsed.tax) noteParts.push(`Tax: $${parsed.tax.toFixed(2)}`);
        if (parsed.tip) noteParts.push(`Tip: $${parsed.tip.toFixed(2)}`);
        
        setFormData(prev => ({
          ...prev,
          date: parsed.date || prev.date,
          category: parsed.category || prev.category,
          sub_category: parsed.sub_category || 'miscellaneous',
          description: parsed.vendor_name || parsed.description || '',
          amount: parsed.amount?.toString() || '',
          notes: noteParts.length > 0 ? noteParts.join(' | ') : '',
        }));
        setParseError('Low confidence in some fields. Please verify the data.');
        toast.warning('Data extracted with low confidence. Please verify.');
        return;
      }

      // Check for success
      if (!data?.success) {
        const message = data?.message || 'We couldn\'t parse this receipt. Please enter details manually.';
        setParseError(message);
        toast.warning(message);
        return;
      }

      // Success - populate form with all extracted data
      const parsed = data.data;
      
      // Build detailed notes from extracted breakdown
      const noteParts: string[] = [];
      if (parsed.location) noteParts.push(`📍 ${parsed.location}`);
      if (parsed.subtotal) noteParts.push(`Subtotal: $${parsed.subtotal.toFixed(2)}`);
      if (parsed.tax) noteParts.push(`Tax: $${parsed.tax.toFixed(2)}`);
      if (parsed.tip) noteParts.push(`Tip: $${parsed.tip.toFixed(2)}`);
      
      setFormData(prev => ({
        ...prev,
        date: parsed.date || prev.date,
        category: parsed.category || prev.category,
        sub_category: parsed.sub_category || 'miscellaneous',
        description: parsed.vendor_name || parsed.description || '',
        amount: parsed.amount?.toString() || '',
        notes: noteParts.length > 0 ? noteParts.join(' | ') : '',
      }));
      
      setParseSuccess(true);
      toast.success(data.message || `Receipt parsed: ${parsed.vendor_name || 'Receipt'}`);
      
    } catch (error) {
      console.error('Parse error:', error);
      setParseError('An unexpected error occurred. Please enter data manually or retake photo.');
      toast.error('Something went wrong');
    } finally {
      setParsing(false);
    }
  };

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleImageSelect(file);
    }
    // Reset input so same file can be selected again
    e.target.value = '';
  };

  const handleReceiptParse = useCallback(async (text: string) => {
    setParsing(true);
    setParseError(null);
    try {
      const { data, error } = await supabase.functions.invoke('parse-booking', {
        body: { text, type: 'receipt' },
      });

      // Handle network-level errors
      if (error) {
        console.error('Network error:', error);
        setParseError('Unable to connect. Please check your connection.');
        toast.error('Connection error');
        return;
      }
      
      if (data?.success && data?.data) {
        const parsed = data.data;
        setFormData(prev => ({
          ...prev,
          date: parsed.date || prev.date,
          category: parsed.category || prev.category,
          sub_category: parsed.sub_category || 'miscellaneous',
          description: parsed.description || parsed.vendor_name || '',
          amount: parsed.amount?.toString() || '',
        }));
        setParseSuccess(true);
        toast.success(data.message || 'Receipt parsed successfully!');
      } else {
        const message = data?.message || 'We couldn\'t parse this text. Please enter details manually.';
        setParseError(message);
        toast.warning(message);
      }
    } catch (error) {
      console.error('Parse error:', error);
      setParseError('An unexpected error occurred. Please try again.');
      toast.error('Something went wrong');
    } finally {
      setParsing(false);
    }
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    
    // Check for files first (images)
    if (e.dataTransfer.files?.length > 0) {
      const file = e.dataTransfer.files[0];
      if (file.type.startsWith('image/')) {
        handleImageSelect(file);
        return;
      }
    }
    
    // Otherwise check for text
    const text = e.dataTransfer.getData('text/plain');
    if (text) {
      handleReceiptParse(text);
    }
  }, [handleReceiptParse, handleImageSelect]);

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'meals': return <Utensils className="w-4 h-4" />;
      case 'transport': return <Car className="w-4 h-4" />;
      case 'activity': return <PartyPopper className="w-4 h-4" />;
      case 'shopping': return <ShoppingBag className="w-4 h-4" />;
      case 'parking': return <ParkingCircle className="w-4 h-4" />;
      default: return <MoreHorizontal className="w-4 h-4" />;
    }
  };

  // v2.1.3: Check if this is a mixed trip (needed for purpose filtering)
  const isMixedTrip = trip?.trip_type === 'mixed';

  // Filter expenses by category first
  const categoryFilteredExpenses = activeCategory === 'all' 
    ? expenses 
    : expenses.filter(e => e.category === activeCategory);

  // Then filter by purpose (only for mixed trips when not "all")
  const filteredExpenses = isMixedTrip && activePurposeFilter !== 'all'
    ? categoryFilteredExpenses.filter(e => e.expense_purpose === activePurposeFilter)
    : categoryFilteredExpenses;

  // v2.1.21: Get normalized per-booking costs for flight expense normalization
  const { perBookingCost, perBookingMyShare } = useMemo(
    () => normalizeFlightBookingCosts(bookings),
    [bookings]
  );

  // v3.9.25: Use canonical cost summary (single source of truth) for summary cards
  // This ensures Trip Total and Expenses Tab always agree.
  const canonicalCosts = useMemo(
    () => calculateTripCostSummary(expenses, bookings, [], homeCurrency),
    [expenses, bookings, homeCurrency]
  );
  
  // v3.9.25: Total = bookingsTotal + out-of-pocket expensesTotal (canonical formula)
  // This matches TripHeaderWidgets / Trip Total card exactly.
  const displayTotalAmount = canonicalCosts.totalCost;
  const displayTotalMyShare = canonicalCosts.totalMyShare;

  // Group by category for summary (always from all expenses)
  const byCategory = calculateCategorySummary(expenses);

  // v2.1.3: Calculate business/personal breakdown for mixed trips
  const purposeBreakdown = isMixedTrip ? calculateExpensePurposeBreakdown(expenses, homeCurrency) : null;

  // Debug logging - runs on every render when expenses change
  useEffect(() => {
    if (expenses.length > 0) {
      const summary = calculateTripCostSummary(expenses, bookings, [], homeCurrency);
      logExpenseDebug(tripId, expenses, summary);
    }
  }, [tripId, expenses, bookings]);

  if (isLoading || bookingsLoading) {
    return <div className="flex justify-center py-8"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div></div>;
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-3">
        {/* Header v1.3.2 */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <h3 className="text-lg font-semibold">Expenses</h3>
          {canWriteExpenses && (
            <Button onClick={() => setDialogOpen(true)} className="h-12 rounded-xl text-sm font-semibold shadow-sm bg-success text-success-foreground hover:bg-success/90 active:bg-success/80 md:h-10 md:rounded-md md:shadow-none md:bg-primary md:text-primary-foreground md:hover:bg-primary/90">
              <Plus className="w-4 h-4 mr-2" />
              Add Expense
            </Button>
          )}
        </div>
        
        {/* Quick-Add Buttons */}
        {canWriteExpenses && (
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={() => setGasDialogOpen(true)}>
              <Fuel className="w-4 h-4 mr-1" />
              Gas
            </Button>
            <Button variant="outline" size="sm" onClick={() => openQuickAdd('meals', 'groceries')}>
              <ShoppingBag className="w-4 h-4 mr-1" />
              Groceries
            </Button>
            <Button variant="outline" size="sm" onClick={() => openQuickAdd('meals', 'breakfast')}>
              <Utensils className="w-4 h-4 mr-1" />
              Breakfast
            </Button>
            <Button variant="outline" size="sm" onClick={() => openQuickAdd('meals', 'lunch')}>
              <Utensils className="w-4 h-4 mr-1" />
              Lunch
            </Button>
            <Button variant="outline" size="sm" onClick={() => openQuickAdd('meals', 'dinner')}>
              <Utensils className="w-4 h-4 mr-1" />
              Dinner
            </Button>
            <Button variant="outline" size="sm" onClick={() => openQuickAdd('other', 'miscellaneous')}>
              <MoreHorizontal className="w-4 h-4 mr-1" />
              Other
            </Button>
          </div>
        )}
      </div>

      {/* Gas Expense Dialog */}
      <GasExpenseDialog 
        tripId={tripId} 
        open={gasDialogOpen} 
        onOpenChange={setGasDialogOpen} 
      />

      {/* Summary Cards */}
      <div className="grid gap-5 md:grid-cols-3">

        {/* v2.1.3: Business vs Personal Summary for Mixed Trips */}
        {isMixedTrip && purposeBreakdown && (
          <div className="md:col-span-3">
            <BusinessPersonalSummary breakdown={purposeBreakdown} />
          </div>
        )}

        {/* v4.4.x: Multi-currency notice */}
        {canonicalCosts.isMultiCurrency && (
          <div className="md:col-span-3">
            <Alert className="border-amber-200 bg-amber-50/60 dark:bg-amber-950/20 dark:border-amber-800">
              <AlertCircle className="h-4 w-4 text-amber-600" />
              <AlertDescription className="text-sm text-amber-800 dark:text-amber-300">
                You have expenses in multiple currencies. Convert to your account currency ({homeCurrency}) before using totals for tax reporting or reimbursement.
              </AlertDescription>
            </Alert>
          </div>
        )}

        <Card>
          <CardHeader className="pb-3">
            <CardDescription>Trip Total</CardDescription>
            {/* v4.4.x: Show per-currency breakdown if multi-currency */}
            {canonicalCosts.isMultiCurrency ? (
              <div className="space-y-1">
                {canonicalCosts.multiCurrency.currencies.map(curr => (
                  <CardTitle key={curr} className="text-lg tabular-nums">
                    {formatCurrency(canonicalCosts.multiCurrency.totals_by_currency[curr], curr)}
                  </CardTitle>
                ))}
              </div>
            ) : (
              <CardTitle className="text-2xl">{formatCurrency(displayTotalAmount)}</CardTitle>
            )}
            <p className="text-[11px] text-muted-foreground tabular-nums mt-1">
              Bookings: {formatCurrency(canonicalCosts.bookingsTotal)} • Out-of-pocket: {formatCurrency(canonicalCosts.expensesTotal)}
            </p>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-3">
            <CardDescription>{MY_SHARE_LABEL}</CardDescription>
            <CardTitle className="text-2xl text-primary">{formatCurrency(displayTotalMyShare)}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-3">
            <CardDescription>Top Category</CardDescription>
            <CardTitle className="text-lg capitalize">
              {Object.entries(byCategory)
                .filter(([_, value]) => value > 0)
                .sort((a, b) => b[1] - a[1])[0]?.[0] || 'None'}
            </CardTitle>
          </CardHeader>
        </Card>
      </div>

      {/* Category Filter Tabs */}
      <Tabs value={activeCategory} onValueChange={setActiveCategory}>
        <TabsList className="flex-wrap h-auto gap-1">
          <TabsTrigger value="all" className="text-xs">All</TabsTrigger>
          <TabsTrigger value="meals" className="text-xs">
            <Utensils className="w-3 h-3 mr-1" />Meals
          </TabsTrigger>
          <TabsTrigger value="transport" className="text-xs">
            <Car className="w-3 h-3 mr-1" />Transport
          </TabsTrigger>
          <TabsTrigger value="activity" className="text-xs">
            <PartyPopper className="w-3 h-3 mr-1" />Activity
          </TabsTrigger>
          <TabsTrigger value="shopping" className="text-xs">
            <ShoppingBag className="w-3 h-3 mr-1" />Shopping
          </TabsTrigger>
          <TabsTrigger value="parking" className="text-xs">
            <ParkingCircle className="w-3 h-3 mr-1" />Parking
          </TabsTrigger>
          <TabsTrigger value="other" className="text-xs">
            <MoreHorizontal className="w-3 h-3 mr-1" />Other
          </TabsTrigger>
        </TabsList>

        {/* v2.1.4: Business/Personal Filter for Mixed Trips */}
        {isMixedTrip && (
          <div className="mt-3 flex items-center gap-2">
            <span className="text-sm text-muted-foreground">Filter by:</span>
            <ToggleGroup 
              type="single" 
              value={activePurposeFilter} 
              onValueChange={(value) => value && setActivePurposeFilter(value as 'all' | 'business' | 'personal')}
              size="sm"
            >
              <ToggleGroupItem value="all" aria-label="Show all expenses" className="text-xs">
                All
              </ToggleGroupItem>
              <ToggleGroupItem value="business" aria-label="Show business expenses" className="text-xs">
                <Briefcase className="w-3 h-3 mr-1" />
                Business
              </ToggleGroupItem>
              <ToggleGroupItem value="personal" aria-label="Show personal expenses" className="text-xs">
                <Home className="w-3 h-3 mr-1" />
                Personal
              </ToggleGroupItem>
            </ToggleGroup>
          </div>
        )}
        <TabsContent value={activeCategory} className="mt-4">
          {filteredExpenses.length > 0 ? (
            <Card>
              <CardContent className="p-0">
                <div className="divide-y">
                  {filteredExpenses.map((expense: Expense) => {
                    const isFromBooking = isAutoGeneratedExpense(expense);
                    const isForeignCurrency = isForeignCurrencyExpense(expense, homeCurrency);
                    const expenseCurrency = (expense as any).currency || homeCurrency;
                    // v1.3.1: Handle click on row for editing (except delete icon)
                    const handleRowClick = (e: React.MouseEvent) => {
                      // Don't open edit if clicking delete button or if user can't edit
                      if (!canEdit || isFromBooking) return;
                      openEdit(expense);
                    };
                    
                    return (
                      <div 
                        key={expense.id} 
                        className={`flex items-center justify-between p-4 hover:bg-muted/50 transition-colors ${
                          canEdit && !isFromBooking ? 'cursor-pointer' : ''
                        } ${isForeignCurrency ? 'bg-amber-50/60 dark:bg-amber-950/20 border-l-2 border-l-amber-400' : ''}`}
                        onClick={handleRowClick}
                      >
                        <div className="flex items-center gap-3">
                          <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${isFromBooking ? 'bg-blue-500/10 text-blue-600' : 'bg-primary/10 text-primary'}`}>
                            {isFromBooking ? <Link2 className="w-4 h-4" /> : getCategoryIcon(expense.category)}
                          </div>
                          <div>
                            <div className="flex items-center gap-2 flex-wrap">
                              <p className="font-medium">
                                {expense.description || (expense.category === 'transport' && expense.sub_category === 'gas' ? 'Gas' : expense.category)}
                              </p>
                              {isFromBooking && (
                                <span className="text-[10px] px-1.5 py-0.5 bg-blue-100 text-blue-700 rounded-full font-medium">
                                  From Booking
                                </span>
                              )}
                              {/* v2.1.3: Origin hint for parsed expenses (receipt, email) */}
                              {!isFromBooking && inferExpenseOrigin(expense.notes) && (
                                <ParseOriginHint origin={inferExpenseOrigin(expense.notes)} />
                              )}
                              {/* v1.3.0: Show Business/Personal badge for mixed trips */}
                              {trip?.trip_type === 'mixed' && expense.expense_purpose && (
                                <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${
                                  expense.expense_purpose === 'business' 
                                    ? 'bg-violet-100 text-violet-700' 
                                    : 'bg-emerald-100 text-emerald-700'
                                }`}>
                                  {expense.expense_purpose === 'business' ? '💼 Business' : '🏠 Personal'}
                                </span>
                              )}
                              {/* v4.4.0: Foreign currency indicator */}
                              {isForeignCurrency && !isConvertedExpense(expense) && (
                                 <span className="text-[10px] px-1.5 py-0.5 bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300 rounded-full font-semibold">
                                  {expenseCurrency} · Convert to {homeCurrency}
                                </span>
                              )}
                              {isForeignCurrency && isConvertedExpense(expense) && (
                                 <span className="text-[10px] px-1.5 py-0.5 bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300 rounded-full font-semibold">
                                  {expenseCurrency} → {formatCurrency(Number(expense.converted_amount))} {homeCurrency}
                                </span>
                              )}
                              {/* v4.4.x: Assumed currency badge */}
                              {!isForeignCurrency && hasCurrencyAssumedFlag(expense.notes) && (
                                <span className="text-[10px] px-1.5 py-0.5 bg-muted text-muted-foreground rounded-full font-medium" title="Currency was not specified in the source document; assumed from your account settings">
                                  Assumed {homeCurrency}
                                </span>
                              )}
                              {/* Patch 2.3.8: Show Stop name when assigned (Business only) */}
                              <BusinessOnly>
                                {expense.engagement_id && (() => {
                                  const stop = engagements.find(e => e.id === expense.engagement_id);
                                  return stop ? (
                                    <span className="text-[10px] px-1.5 py-0.5 bg-accent text-accent-foreground rounded-full font-medium flex items-center gap-0.5">
                                      <MapPin className="w-2.5 h-2.5" />
                                      {stop.name}
                                    </span>
                                  ) : null;
                                })()}
                              </BusinessOnly>
                            </div>
                            <p className="text-sm text-muted-foreground">
                              {format(parseISO(expense.date), 'MMM d, yyyy')}
                              {/* Don't show sub-category for gas since 'Gas' is already displayed as the category */}
                              {expense.sub_category && expense.sub_category !== 'gas' && ` • ${expense.sub_category.replace('_', ' ')}`}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-4">
                          <div className="text-right">
                            {/* v4.4.0: Show amount in original currency for foreign expenses */}
                            <p className={`font-semibold ${isForeignCurrency ? 'text-amber-700 dark:text-amber-400' : ''}`}>
                              {isForeignCurrency 
                                ? formatCurrency(Number(expense.amount || 0), expenseCurrency)
                                : formatCurrency(getNormalizedExpenseAmount(expense, perBookingCost))
                              }
                            </p>
                            {!isForeignCurrency && getNormalizedExpenseMyShare(expense, perBookingMyShare) > 0 && (
                              <p className="text-sm text-muted-foreground">{MY_SHARE_LABEL}: {formatCurrency(getNormalizedExpenseMyShare(expense, perBookingMyShare))}</p>
                            )}
                            {isForeignCurrency && !isConvertedExpense(expense) && (
                              <p className="text-[11px] text-amber-600 dark:text-amber-500 italic">Not in totals</p>
                            )}
                            {isForeignCurrency && isConvertedExpense(expense) && (
                              <p className="text-[11px] text-green-600 dark:text-green-500">Converted · In totals</p>
                            )}
                          </div>
                          {canEdit && !isFromBooking && (
                            <Button
                              variant="ghost"
                              size="icon"
                              className="text-destructive hover:text-destructive"
                              onClick={(e) => {
                                e.stopPropagation(); // v1.3.1: Prevent row click when deleting
                                setExpenseToDelete(expense.id);
                              }}
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          )}
                          {canEdit && isFromBooking && (
                            <span className="text-xs text-muted-foreground italic">
                              Edit via Bookings
                            </span>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </CardContent>
            </Card>
          ) : (
            /* Patch 2.6.1: Improved empty state with clearer guidance */
            <Card className="border-dashed">
              <CardContent className="flex flex-col items-center justify-center py-12">
                <div className="w-14 h-14 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                  <Receipt className="w-7 h-7 text-primary" />
                </div>
                <h4 className="text-base font-medium mb-1">
                  {activeCategory === 'all' ? 'No expenses recorded' : `No ${activeCategory} expenses`}
                </h4>
                <p className="text-sm text-muted-foreground text-center max-w-sm mb-4">
                  {activeCategory === 'all' 
                    ? 'Expenses you add will appear here. Track meals, transport, activities, and shared costs.'
                    : `No expenses in this category yet. Add one or check other categories.`
                  }
                </p>
                {canWriteExpenses && (
                  <Button onClick={() => setDialogOpen(true)} className="h-12 rounded-xl text-sm font-semibold shadow-sm bg-success text-success-foreground hover:bg-success/90 active:bg-success/80 md:h-10 md:rounded-md md:shadow-none md:bg-primary md:text-primary-foreground md:hover:bg-primary/90">
                    <Plus className="w-4 h-4 mr-2" />
                    Add Expense
                  </Button>
                )}
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>

      {/* Add/Edit Expense Dialog - v1.3.1: Unified dialog for create and edit */}
      <Dialog open={dialogOpen} onOpenChange={(open) => { if (!open) { resetForm(); setEditingExpense(null); } setDialogOpen(open); }}>
        <DialogContent className="sm:max-w-md max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingExpense ? 'Edit Expense' : 'Add Expense'}</DialogTitle>
            <DialogDescription>
              {editingExpense ? 'Update the expense details below' : 'Take a photo or drop receipt text to auto-fill'}
            </DialogDescription>
          </DialogHeader>

          {/* Hidden file inputs */}
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={handleFileInputChange}
          />
          <input
            ref={cameraInputRef}
            type="file"
            accept="image/*"
            capture="environment"
            className="hidden"
            onChange={handleFileInputChange}
          />

          {/* Receipt Photo/Upload Section */}
          <div className="space-y-3">
            {/* Action Buttons */}
            <div className="flex gap-2">
              <Button
                type="button"
                variant="outline"
                className="flex-1"
                onClick={() => cameraInputRef.current?.click()}
                disabled={parsing || uploadingImage}
              >
                <Camera className="w-4 h-4 mr-2" />
                Take Photo
              </Button>
              <Button
                type="button"
                variant="outline"
                className="flex-1"
                onClick={() => fileInputRef.current?.click()}
                disabled={parsing || uploadingImage}
              >
                <ImageIcon className="w-4 h-4 mr-2" />
                Upload Image
              </Button>
            </div>

            {/* Drop Zone */}
            <div 
              className={`border-2 border-dashed rounded-lg p-4 text-center transition-colors ${
                parsing || uploadingImage ? 'border-primary bg-primary/5' : 'hover:border-primary/50 cursor-pointer'
              }`}
              onDrop={handleDrop}
              onDragOver={(e) => e.preventDefault()}
              onClick={() => !parsing && !uploadingImage && fileInputRef.current?.click()}
            >
              {parsing ? (
                <div className="flex items-center justify-center gap-2 text-primary">
                  <Sparkles className="w-5 h-5 animate-pulse" />
                  <span>AI is parsing your receipt...</span>
                </div>
              ) : uploadingImage ? (
                <div className="flex items-center justify-center gap-2 text-primary">
                  <RefreshCw className="w-5 h-5 animate-spin" />
                  <span>Uploading image...</span>
                </div>
              ) : (
                <div className="flex flex-col items-center gap-2 text-muted-foreground">
                  <Upload className="w-6 h-6" />
                  <span className="text-sm">Drop receipt image or text here</span>
                </div>
              )}
            </div>

            {/* Preview Image */}
            {previewImage && (
              <div className="relative">
                <img 
                  src={previewImage} 
                  alt="Receipt preview" 
                  className="w-full h-32 object-cover rounded-lg border"
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="absolute top-1 right-1 h-6 w-6 p-0 bg-background/80"
                  onClick={() => {
                    setPreviewImage(null);
                    setFormData(prev => ({ ...prev, receipt_url: '' }));
                  }}
                >
                  <Trash2 className="w-3 h-3" />
                </Button>
              </div>
            )}

            {/* Parse Status Messages */}
            {parseError && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription className="flex items-center justify-between">
                  <span>{parseError}</span>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setParseError(null);
                      cameraInputRef.current?.click();
                    }}
                  >
                    <RefreshCw className="w-3 h-3 mr-1" />
                    Retry
                  </Button>
                </AlertDescription>
              </Alert>
            )}

            {parseSuccess && !parseError && (
              <Alert className="border-green-500 bg-green-50 dark:bg-green-950">
                <CheckCircle className="h-4 w-4 text-green-600" />
                <AlertDescription className="text-green-700 dark:text-green-300">
                  Receipt parsed successfully! Please verify the data below.
                </AlertDescription>
              </Alert>
            )}

            {/* Patch 2.6.7: Contextual education for manual review */}
            {(parseSuccess || parseError) && (
              <ManualStepHint message={MANUAL_STEP_HINTS.expenseReview} />
            )}
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Date *</Label>
                <Input
                  type="date"
                  value={formData.date}
                  onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>Category *</Label>
                <Select 
                  value={formData.category} 
                  onValueChange={(v: ExpenseCategory) => setFormData({ ...formData, category: v, sub_category: '' })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="meals">Meals</SelectItem>
                    <SelectItem value="transport">Transport</SelectItem>
                    <SelectItem value="activity">Activity</SelectItem>
                    <SelectItem value="shopping">Shopping</SelectItem>
                    <SelectItem value="parking">Parking</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {SUB_CATEGORIES[formData.category]?.length > 0 && (
              <div className="space-y-2">
                <Label>Sub-Category</Label>
                <Select 
                  value={formData.sub_category} 
                  onValueChange={(v: ExpenseSubCategory) => setFormData({ ...formData, sub_category: v })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select sub-category" />
                  </SelectTrigger>
                  <SelectContent>
                    {SUB_CATEGORIES[formData.category].map(sub => (
                      <SelectItem key={sub.value} value={sub.value}>{sub.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            {/* v1.3.0: Business/Personal selector for mixed trips only */}
            {trip?.trip_type === 'mixed' && (
              <div className="space-y-2">
                <Label>Expense Type *</Label>
                <Select 
                  value={formData.expense_purpose} 
                  onValueChange={(v: ExpensePurpose) => setFormData({ ...formData, expense_purpose: v })}
                >
                  <SelectTrigger className={!formData.expense_purpose ? 'border-amber-400' : ''}>
                    <SelectValue placeholder="Select Business or Personal" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="business">💼 Business</SelectItem>
                    <SelectItem value="personal">🏠 Personal</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}

            {/* Patch 2.3.8: Stop selector for Business users */}
            <BusinessOnly>
              {engagements.length > 0 && (
                <div className="space-y-2">
                  <Label>Assign to Stop (optional)</Label>
                  <Select 
                    value={formData.engagement_id} 
                    onValueChange={(v) => setFormData({ ...formData, engagement_id: v === 'none' ? '' : v })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Not assigned" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">Not assigned</SelectItem>
                      {engagements.map((engagement) => (
                        <SelectItem key={engagement.id} value={engagement.id}>
                          <div className="flex items-center gap-2">
                            <MapPin className="w-3 h-3" />
                            <span>{engagement.name}</span>
                            <span className="text-muted-foreground text-xs">
                              ({engagement.date})
                            </span>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {/* Patch 2.6.7: Contextual education for stop assignment */}
                  <ManualStepHint message={MANUAL_STEP_HINTS.stopAssignment} />
                </div>
              )}
            </BusinessOnly>

            <div className="space-y-2">
              <Label>Description</Label>
              <Input
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                placeholder="Description"
              />
            </div>

            {/* v4.4.2: Currency selector */}
            <div className="space-y-2">
              <Label>Currency</Label>
              <Select 
                value={formData.currency} 
                onValueChange={(v) => setFormData({ ...formData, currency: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="USD">USD – US Dollar</SelectItem>
                  <SelectItem value="EUR">EUR – Euro</SelectItem>
                  <SelectItem value="GBP">GBP – British Pound</SelectItem>
                  <SelectItem value="CAD">CAD – Canadian Dollar</SelectItem>
                  <SelectItem value="AUD">AUD – Australian Dollar</SelectItem>
                  <SelectItem value="JPY">JPY – Japanese Yen</SelectItem>
                  <SelectItem value="CHF">CHF – Swiss Franc</SelectItem>
                  <SelectItem value="MXN">MXN – Mexican Peso</SelectItem>
                  <SelectItem value="BRL">BRL – Brazilian Real</SelectItem>
                  <SelectItem value="INR">INR – Indian Rupee</SelectItem>
                  <SelectItem value="SEK">SEK – Swedish Krona</SelectItem>
                  <SelectItem value="NOK">NOK – Norwegian Krone</SelectItem>
                  <SelectItem value="DKK">DKK – Danish Krone</SelectItem>
                  <SelectItem value="NZD">NZD – New Zealand Dollar</SelectItem>
                  <SelectItem value="ZAR">ZAR – South African Rand</SelectItem>
                  <SelectItem value="SGD">SGD – Singapore Dollar</SelectItem>
                  <SelectItem value="HKD">HKD – Hong Kong Dollar</SelectItem>
                  <SelectItem value="KRW">KRW – South Korean Won</SelectItem>
                  <SelectItem value="THB">THB – Thai Baht</SelectItem>
                  <SelectItem value="PLN">PLN – Polish Zloty</SelectItem>
                  <SelectItem value="CZK">CZK – Czech Koruna</SelectItem>
                  <SelectItem value="HUF">HUF – Hungarian Forint</SelectItem>
                  <SelectItem value="ILS">ILS – Israeli Shekel</SelectItem>
                  <SelectItem value="TRY">TRY – Turkish Lira</SelectItem>
                  <SelectItem value="AED">AED – UAE Dirham</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Amount ({formData.currency}) *</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={formData.amount}
                  onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                  placeholder="0.00"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>My Share</Label>
                <Input
                  type="number"
                  step="0.01"
                  value={formData.my_share}
                  onChange={(e) => setFormData({ ...formData, my_share: e.target.value })}
                  placeholder="0.00"
                />
              </div>
            </div>

            {/* v4.4.2: Manual conversion section — shown when currency differs from home currency */}
            {formData.currency.toUpperCase() !== homeCurrency.toUpperCase() && (
              <div className="rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-950/20 p-3 space-y-2">
                <div className="flex items-center gap-2">
                  <AlertCircle className="w-4 h-4 text-amber-600" />
                  <p className="text-sm font-medium text-amber-800 dark:text-amber-300">
                    Convert to {homeCurrency}
                  </p>
                </div>
                <p className="text-xs text-muted-foreground">
                  This expense is in {formData.currency}. Enter the equivalent in {homeCurrency} so it's included in your trip totals. 
                  The original {formData.currency} amount is kept for your records.
                </p>
                <div className="space-y-1">
                  <Label className="text-xs">Converted Amount ({homeCurrency})</Label>
                  <Input
                    type="number"
                    step="0.01"
                    value={formData.converted_amount}
                    onChange={(e) => setFormData({ ...formData, converted_amount: e.target.value })}
                    placeholder={`Amount in ${homeCurrency}`}
                    className="h-10"
                  />
                </div>
                {!formData.converted_amount && (
                  <p className="text-[11px] text-amber-600 dark:text-amber-500 italic">
                    Without conversion, this expense won't be included in trip totals.
                  </p>
                )}
              </div>
            )}

            <div className="space-y-2">
              <Label>Notes</Label>
              <Textarea
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                rows={2}
              />
            </div>

            <div className="flex gap-3 pt-4">
              <Button type="button" variant="outline" onClick={() => { resetForm(); setEditingExpense(null); setDialogOpen(false); }} className="flex-1">
                Cancel
              </Button>
              <Button 
                type="submit" 
                className="flex-1 bg-gradient-ocean hover:opacity-90" 
                disabled={editingExpense ? updateExpense.isPending : createExpense.isPending}
              >
                {editingExpense 
                  ? (updateExpense.isPending ? 'Saving...' : 'Save Changes')
                  : (createExpense.isPending ? 'Adding...' : 'Add Expense')
                }
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      <AlertDialog open={!!expenseToDelete} onOpenChange={() => setExpenseToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Expense</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this expense? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
