project_id = "tlrviwlfckiahhfmeilv"

[functions.trip-lifecycle-enforcement]
verify_jwt = false

[functions.parse-booking]
verify_jwt = false

[functions.parse-receipt-image]
verify_jwt = false

[functions.parse-booking-image]
verify_jwt = false

[functions.generate-notifications]
verify_jwt = false

[functions.places-search]
verify_jwt = false

[functions.inbound-email]
verify_jwt = false

[functions.process-pending-import]
verify_jwt = false

[functions.nearby-places]
verify_jwt = false