/**
 * ExpenseCard - Shared presentational card for expense entities
 * 
 * Patch 2.2.3: Mobile-first layout shell & shared cards
 * 
 * A "dumb" component that receives typed props and renders UI.
 * Does NOT call domain hooks - receives all data from containers.
 */

import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { 
  Utensils, 
  Car, 
  PartyPopper, 
  ShoppingBag, 
  ParkingCircle, 
  MoreHorizontal,
  Pencil,
  Trash2,
  Receipt,
  Briefcase,
  Home,
  CloudOff,
} from 'lucide-react';
import { format, parseISO } from 'date-fns';

export type ExpenseCategory = 'meals' | 'transport' | 'activity' | 'shopping' | 'parking' | 'other';
export type ExpensePurpose = 'business' | 'personal';

export interface ExpenseCardProps {
  /** Unique identifier */
  id: string;
  /** Date (YYYY-MM-DD) */
  date: string;
  /** Category */
  category: ExpenseCategory;
  /** Sub-category label */
  subCategory?: string | null;
  /** Description */
  description?: string | null;
  /** Total amount (formatted, e.g., "$50.00") */
  displayAmount: string;
  /** My share if different (formatted) */
  myShareAmount?: string | null;
  /** Notes */
  notes?: string | null;
  /** Receipt URL */
  receiptUrl?: string | null;
  /** Expense purpose for mixed trips */
  expensePurpose?: ExpensePurpose | null;
  /** Stop name if linked to a stop */
  linkedStopName?: string | null;
  /** Whether this is auto-generated from booking */
  isAutoGenerated?: boolean;
  /** v4.0.3: Whether this expense is pending offline sync */
  isPendingSync?: boolean;
  /** Whether this card is highlighted */
  isHighlighted?: boolean;
  /** Can user edit this expense */
  canEdit?: boolean;
  /** Callback for edit action */
  onEdit?: () => void;
  /** Callback for delete action */
  onDelete?: () => void;
  /** Callback for viewing receipt */
  onViewReceipt?: () => void;
  /** Additional class names */
  className?: string;
}

const CATEGORY_ICONS: Record<ExpenseCategory, React.ComponentType<{ className?: string }>> = {
  meals: Utensils,
  transport: Car,
  activity: PartyPopper,
  shopping: ShoppingBag,
  parking: ParkingCircle,
  other: MoreHorizontal,
};

const CATEGORY_COLORS: Record<ExpenseCategory, string> = {
  meals: 'bg-amber-500/10 text-amber-600',
  transport: 'bg-blue-500/10 text-blue-600',
  activity: 'bg-purple-500/10 text-purple-600',
  shopping: 'bg-pink-500/10 text-pink-600',
  parking: 'bg-brand-signal/10 text-brand-signal-deep',
  other: 'bg-gray-500/10 text-gray-600',
};

export function ExpenseCard({
  id,
  date,
  category,
  subCategory,
  description,
  displayAmount,
  myShareAmount,
  notes,
  receiptUrl,
  expensePurpose,
  linkedStopName,
  isAutoGenerated,
  isHighlighted = false,
  isPendingSync = false,
  canEdit = false,
  onEdit,
  onDelete,
  onViewReceipt,
  className,
}: ExpenseCardProps) {
  const IconComponent = CATEGORY_ICONS[category];
  const colorClasses = CATEGORY_COLORS[category];

  // Format date for display
  const formatDate = (dateStr: string) => {
    try {
      return format(parseISO(dateStr), 'MMM d');
    } catch {
      return dateStr;
    }
  };

  // Capitalize category for display
  const displayCategory = category.charAt(0).toUpperCase() + category.slice(1);

  return (
    <Card 
      className={cn(
        "transition-all duration-200",
        "hover:shadow-sm",
        isHighlighted && "ring-2 ring-primary animate-pulse",
        className
      )}
    >
      <CardContent className="py-2.5 px-3 sm:py-3 sm:px-4">
        <div className="flex items-center gap-3">
          {/* Category icon */}
          <div className={cn(
            "shrink-0 w-9 h-9 sm:w-10 sm:h-10 rounded-lg flex items-center justify-center",
            colorClasses
          )}>
            <IconComponent className="w-4 h-4 sm:w-5 sm:h-5" />
          </div>

          {/* Content */}
          <div className="flex-1 min-w-0">
            {/* Title row */}
            <div className="flex items-center gap-1.5 flex-wrap">
              <h4 className="font-medium text-sm truncate">
                {description || subCategory || displayCategory}
              </h4>
              
              {/* Purpose badge for mixed trips */}
              {expensePurpose && (
                <Badge 
                  variant="outline" 
                  className={cn(
                    "text-[10px] px-1.5 py-0 h-4 gap-0.5",
                    expensePurpose === 'business' 
                      ? "border-blue-300 bg-blue-50 text-blue-700"
                      : "border-green-300 bg-green-50 text-green-700"
                  )}
                >
                  {expensePurpose === 'business' ? (
                    <Briefcase className="w-2.5 h-2.5" />
                  ) : (
                    <Home className="w-2.5 h-2.5" />
                  )}
                  {expensePurpose.charAt(0).toUpperCase() + expensePurpose.slice(1)}
                </Badge>
              )}

              {/* Auto-generated indicator */}
              {isAutoGenerated && (
                <Badge variant="secondary" className="text-[10px] px-1 py-0 h-4">
                  Auto
                </Badge>
              )}

              {/* v4.0.3: Pending sync indicator */}
              {isPendingSync && (
                <Badge variant="outline" className="text-[10px] px-1.5 py-0 h-4 gap-0.5 border-orange-300 bg-orange-50 text-orange-700">
                  <CloudOff className="w-2.5 h-2.5" />
                  Pending Sync
                </Badge>
              )}
            </div>

            {/* Metadata row */}
            <div className="flex flex-wrap items-center gap-x-2 gap-y-0.5 text-xs text-muted-foreground mt-0.5">
              <span>{formatDate(date)}</span>
              {subCategory && subCategory !== description && (
                <>
                  <span>•</span>
                  <span className="capitalize">{subCategory.replace(/_/g, ' ')}</span>
                </>
              )}
              {linkedStopName && (
                <>
                  <span>•</span>
                  <span className="truncate max-w-[120px]">{linkedStopName}</span>
                </>
              )}
            </div>

            {/* Notes */}
            {notes && (
              <p className="text-xs text-muted-foreground mt-1 line-clamp-1">
                {notes}
              </p>
            )}
          </div>

          {/* Amount */}
          <div className="text-right shrink-0">
            <div className="font-medium text-sm">{displayAmount}</div>
            {myShareAmount && myShareAmount !== displayAmount && (
              <div className="text-[10px] text-muted-foreground">
                Your share: {myShareAmount}
              </div>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-0.5 shrink-0">
            {receiptUrl && onViewReceipt && (
              <Button
                variant="ghost"
                size="icon"
                onClick={onViewReceipt}
                className="h-7 w-7 sm:h-8 sm:w-8"
                title="View receipt"
              >
                <Receipt className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              </Button>
            )}
            {canEdit && onEdit && (
              <Button
                variant="ghost"
                size="icon"
                onClick={onEdit}
                className="h-7 w-7 sm:h-8 sm:w-8"
                title="Edit"
              >
                <Pencil className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              </Button>
            )}
            {canEdit && onDelete && !isAutoGenerated && (
              <Button
                variant="ghost"
                size="icon"
                onClick={onDelete}
                className="h-7 w-7 sm:h-8 sm:w-8 text-destructive hover:text-destructive"
                title="Delete"
              >
                <Trash2 className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              </Button>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
