/**
 * useBookingExpenseSync — Canonical retroactive expense repair hook
 * 
 * v5.0.0: Hardened PNR-aware grouping with:
 * - Deterministic canonical leg selection (pure string comparison, no Date math)
 * - Strict idempotent expense sync (exactly 1 expense per PNR per trip)
 * - Safe orphan deletion (only auto-generated, never user-modified)
 * - Placeholder [needs_pricing] logic for bookings without cost
 * 
 * ARCHITECTURE:
 * - Runs ONCE per trip load (guarded by ref + dependency check)
 * - Non-blocking: failures are logged, never surfaced as errors
 * - Invalidates ['expenses', tripId] after any repairs
 * - Groups flight bookings by confirmation_number to prevent per-leg expenses
 * - Only touches flight bookings; non-flights pass through unchanged
 */

import { useEffect, useRef } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Booking, Expense } from '@/types/database';
import { supabase } from '@/integrations/supabase/client';
import {
  extractBookingIdFromNotes,
  createBookingLinkMarker,
  mapBookingTypeToExpenseCategory,
  getExpenseDescriptionForBooking,
  hasNeedsPricingFlag,
  isAutoGeneratedExpense,
} from '@/lib/bookingExpenseSync';

// ─── Constants ────────────────────────────────────────────────────────
const NEEDS_PRICING_FLAG = '[needs_pricing]';

// ─── Types ────────────────────────────────────────────────────────────

/** Result of PNR grouping: canonical bookings to sync + IDs to clean up */
export interface PNRGroupingResult {
  /** Bookings that should each have exactly 1 expense */
  canonicalBookings: Booking[];
  /** Booking IDs that are non-canonical legs (their expenses are orphans) */
  nonCanonicalBookingIds: Set<string>;
  /** Map from PNR key -> canonical booking ID */
  pnrCanonicalMap: Map<string, string>;
}

// ─── Pure helpers (exported for testing) ──────────────────────────────

/**
 * Build a PNR hash key for a booking.
 * Format: `${trip_id}::${CONFIRMATION_NUMBER}`
 */
export function buildPNRKey(tripId: string, confirmationNumber: string): string {
  return `${tripId}::${confirmationNumber.trim().toUpperCase()}`;
}

/**
 * Deterministic canonical leg selection using pure string comparison.
 * 1. Compare start_datetime strings (earliest wins).
 * 2. Ties broken by booking ID (lexicographic, for absolute stability).
 * No Date objects. No timezone conversion.
 */
export function selectCanonicalLeg(group: Booking[]): Booking {
  if (group.length === 1) return group[0];

  const sorted = [...group].sort((a, b) => {
    const aTime = a.start_datetime || '';
    const bTime = b.start_datetime || '';
    if (aTime < bTime) return -1;
    if (aTime > bTime) return 1;
    // Tiebreak by ID for absolute determinism
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });

  return sorted[0];
}

/**
 * Hoist the best cost from any leg in the PNR group to the canonical booking.
 * Returns a shallow copy with cost from the best source if needed.
 */
function hoistCostToCanonical(canonical: Booking, group: Booking[]): Booking {
  const canonicalCost = Number(canonical.total_cost);
  if (Number.isFinite(canonicalCost) && canonicalCost > 0) {
    return canonical; // canonical already has cost
  }

  // Find any leg with a valid cost
  const withCost = group.find(b => {
    const c = Number(b.total_cost);
    return Number.isFinite(c) && c > 0;
  });

  if (withCost && withCost.id !== canonical.id) {
    return {
      ...canonical,
      total_cost: withCost.total_cost,
      my_share: withCost.my_share,
    };
  }

  return canonical;
}

/**
 * Group bookings by PNR and determine canonical legs.
 * Pure function — no side effects, no async, no DB calls.
 */
export function getCanonicalBookingPerPNR(bookings: Booking[]): PNRGroupingResult {
  const flights = bookings.filter(b => b.booking_type === 'flight');
  const nonFlights = bookings.filter(b => b.booking_type !== 'flight');

  // Group flights by confirmation_number
  const pnrGroups = new Map<string, Booking[]>();
  const ungroupedFlights: Booking[] = [];

  for (const flight of flights) {
    const conf = (flight.confirmation_number || '').trim().toUpperCase();
    if (!conf || conf.length < 3) {
      ungroupedFlights.push(flight);
      continue;
    }
    const key = buildPNRKey(flight.trip_id, conf);
    if (!pnrGroups.has(key)) pnrGroups.set(key, []);
    pnrGroups.get(key)!.push(flight);
  }

  const canonicalBookings: Booking[] = [...nonFlights, ...ungroupedFlights];
  const nonCanonicalBookingIds = new Set<string>();
  const pnrCanonicalMap = new Map<string, string>();

  for (const [pnrKey, group] of pnrGroups) {
    const canonical = selectCanonicalLeg(group);
    const withCost = hoistCostToCanonical(canonical, group);

    canonicalBookings.push(withCost);
    pnrCanonicalMap.set(pnrKey, canonical.id);

    for (const b of group) {
      if (b.id !== canonical.id) {
        nonCanonicalBookingIds.add(b.id);
      }
    }
  }

  return { canonicalBookings, nonCanonicalBookingIds, pnrCanonicalMap };
}

/**
 * Check if an expense was modified by the user (amount changed from auto-generated value,
 * or has user-entered notes beyond the markers).
 * 
 * Conservative: if uncertain, returns true (treat as user-modified → don't delete).
 */
export function isUserModifiedExpense(expense: Expense): boolean {
  // If it's not auto-generated at all, it's user-created → never delete
  if (!isAutoGeneratedExpense(expense)) return true;

  // Check for user-added notes beyond markers
  const notes = expense.notes || '';
  const cleanedNotes = notes
    .replace(/\[linked_booking:[^\]]+\]/g, '')
    .replace(/\[needs_pricing\]/g, '')
    .trim();

  // If there are user-written notes beyond markers, treat as modified
  if (cleanedNotes.length > 0) return true;

  // Check for manual currency conversion (user intervention)
  if (expense.converted_amount != null && Number(expense.converted_amount) > 0) return true;

  // Check for manual receipt attachment
  if (expense.receipt_url) return true;

  // Check for manual expense purpose assignment
  if (expense.expense_purpose) return true;

  return false;
}

/**
 * Determine if an orphan expense is safe to delete.
 * ALL conditions must be true:
 * 1. Linked to a non-canonical booking ID
 * 2. Is auto-generated (has [linked_booking:...] marker)
 * 3. NOT user-modified
 */
export function isSafeToDeleteOrphan(
  expense: Expense,
  nonCanonicalBookingIds: Set<string>
): boolean {
  const linkedId = extractBookingIdFromNotes(expense.notes);
  if (!linkedId) return false;
  if (!nonCanonicalBookingIds.has(linkedId)) return false;
  if (isUserModifiedExpense(expense)) return false;
  return true;
}

// ─── Hook ─────────────────────────────────────────────────────────────

interface UseBookingExpenseSyncOptions {
  tripId: string;
  bookings: Booking[];
  expenses: Expense[];
  bookingsLoading: boolean;
  expensesLoading: boolean;
  homeCurrency: string;
}

/**
 * Canonical hook that ensures every booking/PNR has exactly one linked expense.
 * Must be called at the container/shell level, NOT inside tab components.
 * 
 * Idempotent: running multiple times produces the same state.
 */
export function useBookingExpenseSync({
  tripId,
  bookings,
  expenses,
  bookingsLoading,
  expensesLoading,
  homeCurrency,
}: UseBookingExpenseSyncOptions): void {
  const queryClient = useQueryClient();
  const syncAttemptedRef = useRef(false);
  const tripIdRef = useRef(tripId);

  // Reset when tripId changes
  if (tripIdRef.current !== tripId) {
    tripIdRef.current = tripId;
    syncAttemptedRef.current = false;
  }

  useEffect(() => {
    if (syncAttemptedRef.current || bookingsLoading || expensesLoading || !bookings.length) return;

    const { canonicalBookings, nonCanonicalBookingIds } = getCanonicalBookingPerPNR(bookings);

    // Build map: booking ID -> linked expenses
    const expensesByLinkedBooking = new Map<string, Expense[]>();
    for (const e of expenses) {
      const linkedId = extractBookingIdFromNotes(e.notes);
      if (linkedId) {
        if (!expensesByLinkedBooking.has(linkedId)) expensesByLinkedBooking.set(linkedId, []);
        expensesByLinkedBooking.get(linkedId)!.push(e);
      }
    }

    // Collect all linked canonical booking IDs
    const canonicalBookingIds = new Set(canonicalBookings.map(b => b.id));

    // ── Phase 1: Identify canonical bookings needing expense creation ──
    const toCreate: Booking[] = [];
    const toUpdate: Array<{ booking: Booking; existingExpense: Expense }> = [];

    for (const booking of canonicalBookings) {
      const linkedExpenses = expensesByLinkedBooking.get(booking.id) || [];

      if (linkedExpenses.length === 0) {
        toCreate.push(booking);
      } else if (linkedExpenses.length === 1) {
        // Check if update needed (cost or currency drift)
        const existing = linkedExpenses[0];
        const bookingCost = getValidCost(booking.total_cost);
        const existingAmount = Number(existing.amount || 0);
        const existingNeedsPricing = hasNeedsPricingFlag(existing.notes);

        // Update if: cost appeared (was placeholder), cost changed, or currency changed
        const costAppeared = existingNeedsPricing && bookingCost > 0;
        const costChanged = !existingNeedsPricing && bookingCost > 0 && Math.abs(existingAmount - bookingCost) > 0.01;

        if (costAppeared || costChanged) {
          // Only update auto-generated expenses, never user-modified ones
          if (!isUserModifiedExpense(existing)) {
            toUpdate.push({ booking, existingExpense: existing });
          }
        }
      }
      // If linkedExpenses.length > 1, dedup handled in Phase 2
    }

    // ── Phase 2: Identify orphan expenses to delete ──
    const toDelete: Expense[] = [];

    // 2a: Expenses linked to non-canonical legs
    for (const e of expenses) {
      if (isSafeToDeleteOrphan(e, nonCanonicalBookingIds)) {
        toDelete.push(e);
      }
    }

    // 2b: Duplicate expenses for the same canonical booking (keep earliest)
    for (const booking of canonicalBookings) {
      const linkedExpenses = expensesByLinkedBooking.get(booking.id) || [];
      if (linkedExpenses.length <= 1) continue;

      // Keep the earliest created, delete others (only if auto-generated + not user-modified)
      const sorted = [...linkedExpenses].sort((a, b) => {
        if (a.created_at < b.created_at) return -1;
        if (a.created_at > b.created_at) return 1;
        return a.id < b.id ? -1 : 1;
      });

      for (let i = 1; i < sorted.length; i++) {
        if (!isUserModifiedExpense(sorted[i])) {
          toDelete.push(sorted[i]);
        }
      }
    }

    // ── Check if any work needed ──
    if (toCreate.length === 0 && toUpdate.length === 0 && toDelete.length === 0) {
      syncAttemptedRef.current = true;
      return;
    }

    syncAttemptedRef.current = true;

    // ── Execute in background — non-blocking ──
    (async () => {
      let changed = 0;

      // Create missing canonical expenses
      for (const booking of toCreate) {
        try {
          await createCanonicalExpense(booking, homeCurrency);
          changed++;
        } catch {
          console.warn('[useBookingExpenseSync] Failed to create expense for booking', booking.id);
        }
      }

      // Update existing expenses with new cost data
      for (const { booking, existingExpense } of toUpdate) {
        try {
          await updateCanonicalExpense(booking, existingExpense, homeCurrency);
          changed++;
        } catch {
          console.warn('[useBookingExpenseSync] Failed to update expense', existingExpense.id);
        }
      }

      // Delete orphan/duplicate expenses
      // Deduplicate by ID to avoid double-delete
      const deleteIds = new Set(toDelete.map(e => e.id));
      for (const id of deleteIds) {
        try {
          await supabase.from('expenses').delete().eq('id', id);
          changed++;
        } catch {
          console.warn('[useBookingExpenseSync] Failed to delete orphan expense', id);
        }
      }

      if (changed > 0) {
        queryClient.invalidateQueries({ queryKey: ['expenses', tripId] });
      }
    })();
  }, [bookings, expenses, bookingsLoading, expensesLoading, homeCurrency, tripId, queryClient]);
}

// ─── Internal helpers ─────────────────────────────────────────────────

/** Validate and return a cost, or 0 if invalid */
function getValidCost(raw: unknown): number {
  if (raw === null || raw === undefined) return 0;
  const num = Number(raw);
  if (!Number.isFinite(num) || num <= 0) return 0;
  return num;
}

/** Create a new canonical expense for a booking */
async function createCanonicalExpense(booking: Booking, homeCurrency: string): Promise<void> {
  const cost = getValidCost(booking.total_cost);
  const needsPricing = cost <= 0;
  const marker = createBookingLinkMarker(booking.id);
  const notes = needsPricing ? `${marker} ${NEEDS_PRICING_FLAG}` : marker;
  const category = mapBookingTypeToExpenseCategory(booking.booking_type);
  const description = getExpenseDescriptionForBooking(booking);

  // Extract date via string slice — no Date construction
  const rawStart = booking.start_datetime || '';
  const expenseDate = rawStart.length >= 10
    ? rawStart.substring(0, 10)
    : '2000-01-01'; // fallback, should never happen

  const rawMyShare = booking.my_share != null ? Number(booking.my_share) : null;
  const safeMyShare = (rawMyShare != null && Number.isFinite(rawMyShare) && rawMyShare > 0) ? rawMyShare : cost;

  await supabase.from('expenses').insert({
    trip_id: booking.trip_id,
    date: expenseDate,
    category,
    description,
    amount: cost,
    my_share: safeMyShare,
    currency: homeCurrency || 'USD',
    notes,
  });
}

/** Update an existing canonical expense with new cost data */
async function updateCanonicalExpense(
  booking: Booking,
  existing: Expense,
  homeCurrency: string
): Promise<void> {
  const cost = getValidCost(booking.total_cost);
  const needsPricing = cost <= 0;

  const rawMyShare = booking.my_share != null ? Number(booking.my_share) : null;
  const safeMyShare = (rawMyShare != null && Number.isFinite(rawMyShare) && rawMyShare > 0) ? rawMyShare : cost;

  // Remove needs_pricing flag if we now have a real cost
  let updatedNotes = existing.notes || '';
  if (!needsPricing) {
    updatedNotes = updatedNotes.replace(NEEDS_PRICING_FLAG, '').trim();
  }

  await supabase.from('expenses').update({
    amount: cost,
    my_share: safeMyShare,
    currency: homeCurrency || 'USD',
    notes: updatedNotes,
  }).eq('id', existing.id);
}
