 /**
  * v2.2.0: Booking-expense sync tests
  * Tests for the booking-expense linking utilities
  */
 
 import { describe, it, expect } from 'vitest';
 import {
   createBookingLinkMarker,
   extractBookingIdFromNotes,
   isExpenseLinkedToBooking,
   mapBookingTypeToExpenseCategory,
   getExpenseDescriptionForBooking,
   isAutoGeneratedExpense,
   getCleanNotesForDisplay,
 } from '../bookingExpenseSync';
 import { Expense, Booking } from '@/types/database';
 
 // Helper to create mock expense
 const mockExpense = (overrides: Partial<Expense> = {}): Expense => ({
   id: 'exp-1',
   trip_id: 'trip-1',
   date: '2026-01-15',
   category: 'meals',
   amount: 100,
   my_share: 50,
   created_at: '2026-01-01T00:00:00Z',
   updated_at: '2026-01-01T00:00:00Z',
   ...overrides,
 });
 
 // Helper to create mock booking
 const mockBooking = (overrides: Partial<Booking> = {}): Booking => ({
   id: 'book-1',
   trip_id: 'trip-1',
   booking_type: 'flight',
   vendor_name: 'Test Airline',
   start_datetime: '2026-01-15T10:00:00Z',
   total_cost: 500,
   my_share: 250,
   created_at: '2026-01-01T00:00:00Z',
   updated_at: '2026-01-01T00:00:00Z',
   ...overrides,
 });
 
 describe('createBookingLinkMarker', () => {
   it('creates marker in correct format', () => {
     const marker = createBookingLinkMarker('abc-123');
     expect(marker).toBe('[linked_booking:abc-123]');
   });
 
   it('handles UUID format', () => {
     const marker = createBookingLinkMarker('550e8400-e29b-41d4-a716-446655440000');
     expect(marker).toBe('[linked_booking:550e8400-e29b-41d4-a716-446655440000]');
   });
 });
 
 describe('extractBookingIdFromNotes', () => {
   it('extracts booking ID from notes', () => {
     const id = extractBookingIdFromNotes('[linked_booking:abc-123]');
     expect(id).toBe('abc-123');
   });
 
   it('extracts ID when marker is embedded in text', () => {
     const id = extractBookingIdFromNotes('Flight booking [linked_booking:abc-123] some notes');
     expect(id).toBe('abc-123');
   });
 
   it('returns null for notes without marker', () => {
     expect(extractBookingIdFromNotes('Regular notes')).toBeNull();
   });
 
   it('returns null for null/undefined notes', () => {
     expect(extractBookingIdFromNotes(null)).toBeNull();
     expect(extractBookingIdFromNotes(undefined)).toBeNull();
   });
 
   it('returns null for incomplete marker', () => {
     expect(extractBookingIdFromNotes('[linked_booking:abc-123')).toBeNull();
     expect(extractBookingIdFromNotes('linked_booking:abc-123]')).toBeNull();
   });
 });
 
 describe('isExpenseLinkedToBooking', () => {
   it('returns true when expense is linked to specific booking', () => {
     const expense = mockExpense({ notes: '[linked_booking:book-1]' });
     expect(isExpenseLinkedToBooking(expense, 'book-1')).toBe(true);
   });
 
   it('returns false when expense is linked to different booking', () => {
     const expense = mockExpense({ notes: '[linked_booking:book-1]' });
     expect(isExpenseLinkedToBooking(expense, 'book-2')).toBe(false);
   });
 
   it('returns false when expense is not linked', () => {
     const expense = mockExpense({ notes: 'Regular notes' });
     expect(isExpenseLinkedToBooking(expense, 'book-1')).toBe(false);
   });
 });
 
 describe('mapBookingTypeToExpenseCategory', () => {
   it('maps flight to transport', () => {
     expect(mapBookingTypeToExpenseCategory('flight')).toBe('transport');
   });
 
   it('maps car_rental to transport', () => {
     expect(mapBookingTypeToExpenseCategory('car_rental')).toBe('transport');
   });
 
   it('maps stay to other', () => {
     expect(mapBookingTypeToExpenseCategory('stay')).toBe('other');
   });
 
   it('maps parking to parking', () => {
     expect(mapBookingTypeToExpenseCategory('parking')).toBe('parking');
   });
 
   it('maps activity to activity', () => {
     expect(mapBookingTypeToExpenseCategory('activity')).toBe('activity');
   });
 
   it('maps unknown to other', () => {
     expect(mapBookingTypeToExpenseCategory('unknown_type')).toBe('other');
   });
 });
 
 describe('getExpenseDescriptionForBooking', () => {
   it('formats flight with airline', () => {
     const booking = mockBooking({ booking_type: 'flight', airline: 'Delta', vendor_name: 'Delta Airlines' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Delta Flight');
   });
 
   it('formats flight without airline', () => {
     const booking = mockBooking({ booking_type: 'flight', airline: undefined, vendor_name: 'Some Airline' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Flight - Some Airline');
   });
 
   it('formats stay with property name', () => {
     const booking = mockBooking({ booking_type: 'stay', property_name: 'Grand Hotel', vendor_name: 'Hotels.com' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Grand Hotel');
   });
 
   it('formats stay without property name', () => {
     const booking = mockBooking({ booking_type: 'stay', property_name: undefined, vendor_name: 'Airbnb' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Stay - Airbnb');
   });
 
   it('formats car rental with company', () => {
     const booking = mockBooking({ booking_type: 'car_rental', rental_company: 'Hertz', vendor_name: 'Hertz Rental' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Hertz');
   });
 
   it('formats activity', () => {
     const booking = mockBooking({ booking_type: 'activity', vendor_name: 'Theme Park' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Activity - Theme Park');
   });
 });
 
 describe('isAutoGeneratedExpense', () => {
   it('returns true for expenses with booking link', () => {
     const expense = mockExpense({ notes: '[linked_booking:book-1]' });
     expect(isAutoGeneratedExpense(expense)).toBe(true);
   });
 
   it('returns false for manual expenses', () => {
     const expense = mockExpense({ notes: 'Manual expense note' });
     expect(isAutoGeneratedExpense(expense)).toBe(false);
   });
 });
 
 describe('getCleanNotesForDisplay', () => {
   it('removes booking link marker from notes', () => {
     const clean = getCleanNotesForDisplay('[linked_booking:abc-123]');
     expect(clean).toBe('');
   });
 
   it('preserves text before and after marker', () => {
     const clean = getCleanNotesForDisplay('Before [linked_booking:abc-123] After');
     expect(clean).toBe('Before After');
   });
 
   it('returns original notes when no marker present', () => {
     const clean = getCleanNotesForDisplay('Regular notes');
     expect(clean).toBe('Regular notes');
   });
 
   it('handles null/undefined', () => {
     expect(getCleanNotesForDisplay(null)).toBe('');
     expect(getCleanNotesForDisplay(undefined)).toBe('');
   });
 });