/**
 * v2.2.1: Booking-expense sync tests
 * Tests for the booking-expense linking utilities
 * 
 * Includes tests for:
 * - Basic marker creation/extraction
 * - Booking type to expense category mapping
 * - Multi-leg flight fare allocation (v2.2.1)
 * - Edge cases for cost normalization
 */

import { describe, it, expect } from 'vitest';
import {
  createBookingLinkMarker,
  extractBookingIdFromNotes,
  isExpenseLinkedToBooking,
  mapBookingTypeToExpenseCategory,
  getExpenseDescriptionForBooking,
  isAutoGeneratedExpense,
  getCleanNotesForDisplay,
  getBookingExpenseCost,
} from '../bookingExpenseSync';
import { Expense, Booking } from '@/types/database';

// Helper to create mock expense
const mockExpense = (overrides: Partial<Expense> = {}): Expense => ({
  id: 'exp-1',
  trip_id: 'trip-1',
  date: '2026-01-15',
  category: 'meals',
  amount: 100,
  my_share: 50,
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
  ...overrides,
});

// Helper to create mock booking
const mockBooking = (overrides: Partial<Booking> = {}): Booking => ({
  id: 'book-1',
  trip_id: 'trip-1',
  booking_type: 'flight',
  vendor_name: 'Test Airline',
  start_datetime: '2026-01-15T10:00:00Z',
  total_cost: 500,
  my_share: 250,
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
  ...overrides,
});
 
 describe('createBookingLinkMarker', () => {
   it('creates marker in correct format', () => {
     const marker = createBookingLinkMarker('abc-123');
     expect(marker).toBe('[linked_booking:abc-123]');
   });
 
   it('handles UUID format', () => {
     const marker = createBookingLinkMarker('550e8400-e29b-41d4-a716-446655440000');
     expect(marker).toBe('[linked_booking:550e8400-e29b-41d4-a716-446655440000]');
   });
 });
 
 describe('extractBookingIdFromNotes', () => {
   it('extracts booking ID from notes', () => {
     const id = extractBookingIdFromNotes('[linked_booking:abc-123]');
     expect(id).toBe('abc-123');
   });
 
   it('extracts ID when marker is embedded in text', () => {
     const id = extractBookingIdFromNotes('Flight booking [linked_booking:abc-123] some notes');
     expect(id).toBe('abc-123');
   });
 
   it('returns null for notes without marker', () => {
     expect(extractBookingIdFromNotes('Regular notes')).toBeNull();
   });
 
   it('returns null for null/undefined notes', () => {
     expect(extractBookingIdFromNotes(null)).toBeNull();
     expect(extractBookingIdFromNotes(undefined)).toBeNull();
   });
 
   it('returns null for incomplete marker', () => {
     expect(extractBookingIdFromNotes('[linked_booking:abc-123')).toBeNull();
     expect(extractBookingIdFromNotes('linked_booking:abc-123]')).toBeNull();
   });
 });
 
 describe('isExpenseLinkedToBooking', () => {
   it('returns true when expense is linked to specific booking', () => {
     const expense = mockExpense({ notes: '[linked_booking:book-1]' });
     expect(isExpenseLinkedToBooking(expense, 'book-1')).toBe(true);
   });
 
   it('returns false when expense is linked to different booking', () => {
     const expense = mockExpense({ notes: '[linked_booking:book-1]' });
     expect(isExpenseLinkedToBooking(expense, 'book-2')).toBe(false);
   });
 
   it('returns false when expense is not linked', () => {
     const expense = mockExpense({ notes: 'Regular notes' });
     expect(isExpenseLinkedToBooking(expense, 'book-1')).toBe(false);
   });
 });
 
 describe('mapBookingTypeToExpenseCategory', () => {
   it('maps flight to transport', () => {
     expect(mapBookingTypeToExpenseCategory('flight')).toBe('transport');
   });
 
   it('maps car_rental to transport', () => {
     expect(mapBookingTypeToExpenseCategory('car_rental')).toBe('transport');
   });
 
   it('maps stay to other', () => {
     expect(mapBookingTypeToExpenseCategory('stay')).toBe('other');
   });
 
   it('maps parking to parking', () => {
     expect(mapBookingTypeToExpenseCategory('parking')).toBe('parking');
   });
 
   it('maps activity to activity', () => {
     expect(mapBookingTypeToExpenseCategory('activity')).toBe('activity');
   });
 
   it('maps unknown to other', () => {
     expect(mapBookingTypeToExpenseCategory('unknown_type')).toBe('other');
   });
 });
 
 describe('getExpenseDescriptionForBooking', () => {
   it('formats flight with airline', () => {
     const booking = mockBooking({ booking_type: 'flight', airline: 'Delta', vendor_name: 'Delta Airlines' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Delta Flight');
   });
 
   it('formats flight without airline', () => {
     const booking = mockBooking({ booking_type: 'flight', airline: undefined, vendor_name: 'Some Airline' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Flight - Some Airline');
   });
 
   it('formats stay with property name', () => {
     const booking = mockBooking({ booking_type: 'stay', property_name: 'Grand Hotel', vendor_name: 'Hotels.com' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Grand Hotel');
   });
 
   it('formats stay without property name', () => {
     const booking = mockBooking({ booking_type: 'stay', property_name: undefined, vendor_name: 'Airbnb' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Stay - Airbnb');
   });
 
   it('formats car rental with company', () => {
     const booking = mockBooking({ booking_type: 'car_rental', rental_company: 'Hertz', vendor_name: 'Hertz Rental' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Hertz');
   });
 
   it('formats activity', () => {
     const booking = mockBooking({ booking_type: 'activity', vendor_name: 'Theme Park' });
     expect(getExpenseDescriptionForBooking(booking)).toBe('Activity - Theme Park');
   });
 });
 
 describe('isAutoGeneratedExpense', () => {
   it('returns true for expenses with booking link', () => {
     const expense = mockExpense({ notes: '[linked_booking:book-1]' });
     expect(isAutoGeneratedExpense(expense)).toBe(true);
   });
 
   it('returns false for manual expenses', () => {
     const expense = mockExpense({ notes: 'Manual expense note' });
     expect(isAutoGeneratedExpense(expense)).toBe(false);
   });
 });
 
 describe('getCleanNotesForDisplay', () => {
   it('removes booking link marker from notes', () => {
     const clean = getCleanNotesForDisplay('[linked_booking:abc-123]');
     expect(clean).toBe('');
   });
 
   it('preserves text before and after marker', () => {
     const clean = getCleanNotesForDisplay('Before [linked_booking:abc-123] After');
     expect(clean).toBe('Before After');
   });
 
   it('returns original notes when no marker present', () => {
     const clean = getCleanNotesForDisplay('Regular notes');
     expect(clean).toBe('Regular notes');
   });
 
  it('handles null/undefined', () => {
    expect(getCleanNotesForDisplay(null)).toBe('');
    expect(getCleanNotesForDisplay(undefined)).toBe('');
  });
});

// ============================================================
// v2.2.1: MULTI-LEG FLIGHT FARE ALLOCATION TESTS
// ============================================================

describe('getBookingExpenseCost', () => {
  describe('multi-leg booking with single total fare', () => {
    it('returns booking total_cost as the expense amount', () => {
      // Scenario: Round-trip flight with 2 segments, single total of $500
      const booking = mockBooking({
        booking_type: 'flight',
        total_cost: 500,
        // Note: In real data, segment info would be in notes or separate records
        // but the booking.total_cost is the single source of truth
      });
      
      expect(getBookingExpenseCost(booking)).toBe(500);
    });

    it('uses booking total for multi-segment flights', () => {
      // Scenario: 3-leg flight (e.g., A->B->C and back) with single total
      const booking = mockBooking({
        booking_type: 'flight',
        airline: 'United',
        total_cost: 750,
        notes: 'Outbound: UA123, UA456. Return: UA789',
      });
      
      // Only the booking-level total is used, not multiplied by legs
      expect(getBookingExpenseCost(booking)).toBe(750);
    });
  });

  describe('booking without total (segment prices only scenario)', () => {
    it('returns 0 when total_cost is null', () => {
      const booking = mockBooking({
        booking_type: 'flight',
        total_cost: null as unknown as number,
      });
      
      // No expense should be created - returns 0
      expect(getBookingExpenseCost(booking)).toBe(0);
    });

    it('returns 0 when total_cost is undefined', () => {
      const booking = mockBooking({
        booking_type: 'flight',
        total_cost: undefined as unknown as number,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(0);
    });

    it('returns 0 when total_cost is 0', () => {
      const booking = mockBooking({
        booking_type: 'flight',
        total_cost: 0,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(0);
    });
  });

  describe('booking with both total and segment amounts present', () => {
    it('uses only booking total, ignores segment data', () => {
      // Scenario: Booking has total_cost = 400
      // Segments might have individual amounts but we ignore them
      const booking = mockBooking({
        booking_type: 'flight',
        total_cost: 400,
        notes: 'Leg 1: $200, Leg 2: $200', // This is just informational
      });
      
      // Only booking.total_cost is used
      expect(getBookingExpenseCost(booking)).toBe(400);
    });
  });

  describe('edge cases for fare normalization', () => {
    it('handles negative cost (treats as invalid)', () => {
      const booking = mockBooking({
        total_cost: -100,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(0);
    });

    it('handles NaN cost', () => {
      const booking = mockBooking({
        total_cost: NaN,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(0);
    });

    it('handles Infinity cost', () => {
      const booking = mockBooking({
        total_cost: Infinity,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(0);
    });

    it('handles string coerced to number', () => {
      const booking = mockBooking({
        total_cost: '350.50' as unknown as number,
      });
      
      // Number() coercion should work
      expect(getBookingExpenseCost(booking)).toBe(350.50);
    });

    it('handles decimal values correctly', () => {
      const booking = mockBooking({
        total_cost: 299.99,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(299.99);
    });
  });

  describe('non-flight bookings', () => {
    it('uses total_cost for stay bookings', () => {
      const booking = mockBooking({
        booking_type: 'stay',
        property_name: 'Grand Hotel',
        total_cost: 450,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(450);
    });

    it('uses total_cost for car rental bookings', () => {
      const booking = mockBooking({
        booking_type: 'car_rental',
        rental_company: 'Hertz',
        total_cost: 275,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(275);
    });

    it('uses total_cost for activity bookings', () => {
      const booking = mockBooking({
        booking_type: 'activity',
        vendor_name: 'Theme Park',
        total_cost: 120,
      });
      
      expect(getBookingExpenseCost(booking)).toBe(120);
    });
  });
});

// ============================================================
// v2.2.1: TRIP TOTAL VERIFICATION TESTS
// These tests verify that totals use expense records, not raw segments
// ============================================================

describe('airfare expense creation logic', () => {
  it('creates exactly one expense for a multi-leg booking', () => {
    // This tests the conceptual flow - syncExpenseFromBooking creates ONE expense
    // per booking, using getBookingExpenseCost for the amount
    const multiLegBooking = mockBooking({
      id: 'booking-roundtrip-1',
      booking_type: 'flight',
      airline: 'Delta',
      total_cost: 500,
      notes: 'Outbound: DL100, DL200. Return: DL300, DL400', // 4 segments
    });
    
    // The cost that would be used for the expense
    const expenseCost = getBookingExpenseCost(multiLegBooking);
    
    // Should be exactly 500, not 500*4 or 500*2
    expect(expenseCost).toBe(500);
  });

  it('prevents double counting by using booking-level total only', () => {
    // Simulate a scenario where we might accidentally double count
    const outboundLeg = mockBooking({
      id: 'leg-1',
      total_cost: 500, // Same total on each "leg" would be wrong
    });
    const returnLeg = mockBooking({
      id: 'leg-2',
      total_cost: 500,
    });
    
    // In correct implementation, these should be ONE booking with total_cost: 500
    // Not TWO bookings with total_cost: 500 each
    // The parsing rules ensure this, but we verify the cost function handles it
    expect(getBookingExpenseCost(outboundLeg)).toBe(500);
    expect(getBookingExpenseCost(returnLeg)).toBe(500);
    
    // Total if incorrectly stored as separate bookings: 1000 (WRONG)
    // Total if correctly stored as single booking: 500 (CORRECT)
    // The fix ensures parsing creates ONE booking with the total
  });
});